### PR TITLE
Feature/#55 add build and push

### PR DESCRIPTION
**Pull request by tuxBurner**
I added build and push as goal.
Also added the request from #54 because i needed this on my own build.

### CODE REVIEW

**Comment by tuxBurner** [comment]
Hmmm last travis build had some weird failure. Could not download an artifact.

**Comment by dkanejs** [comment]
Hey @tuxBurner, thanks for the PR.

I had to resolve some conflicts after a cleanup but LGTM (after some _small_ changes) 👍

Thanks again 👋

**Comment by dkanejs** [comment]
Fixed #56

**Comment by tuxBurner** [comment]
Thx @dkanejs :)

**Pull request merged**
