### PR TITLE
Allow to pass additional parameters for up and down commands

### PR DESCRIPTION
**Pull request by augi**
As discussed in #40

### CODE REVIEW

**Comment by dkanejs** [comment]
Hey @augi, thanks for the PR and so far this looks great but it needs some tests 😄

**Comment by dkanejs** [comment]
Yeah, if you could add some tests that would be grand 👍

**Comment by samixchoumi** [comment]
Hello, this commit isn't available on the version 3.0.0. Is that normal ? Because i want to add the `--abort-on-container-exit` but the `upAdditionalParameters` isn't working right now.

**Comment by dkanejs** [comment]
Hey, yeah this was never merged. It sat waiting for tests that never got added.

It was closed as the PR was stale.

**Comment by samixchoumi** [comment]
Is that possible that it will be implemented soon ? Or there is any way to add parameter like `--abort-on-container-exit` using your plugin on maven ?

**Pull request closed without merging**
