### PR TITLE
add await feature

### PR DESCRIPTION
**Pull request by joachimbjorklund**
Hi, added a simple "wait-for" functionality, need that in my integration-tests.

### CODE REVIEW

**Comment by dkanejs** [comment]
Hey @joachimbjorklund Thanks for the PR I'll give this a look when I get a chance 👍

**Comment by joachimbjorklund** [comment]
You’re welcome, I use the plugin rather often 😀

rgds
Joachim

**Comment by Islandas** [comment]
Hello, 
could you add a short explanation  on how to use it?

**Comment by jockebjork** [comment]
With an executable pointed by the <waitCmd> configuration, the plugin will not exit until the "waitCmd" exits with 0 as exit-code. 

If the "waitCmd" does not exit with 0, within a default, or configured, period of time an exception will be thrown, thus making the plugin itself exit with a non-zero exit-code.

This can be useful for instance when running the plugin in the Maven pre-integration-test phase, thus not starting the testing until the plugin exits (with 0)

Check out the code for further details :)

- Joachim

**Pull request merged**
