### PR TITLE
Feature/support compose down rmi

### PR DESCRIPTION
**Pull request by marcoerdmann**
Hey David,

I added support for docker-compose up --build and docker-compose down --rmi all (I needed this for our Spring Boot Docker deployment). Paolo beat me on the first option but the latter might still be useful to someone. This is my first PR on GitHub, so I hope everything works out.

Regards,

Marco

### CODE REVIEW

**Comment by dkanejs** [comment]
Fixes #22

**Comment by marcoerdmann** [comment]
Hey, I rebased to your current master and merged so the conflicts should be fixed now.

**Comment by dkanejs** [comment]
Thanks again for your work 🥇

**Comment by marcoerdmann** [comment]
Thanks for merging. I am looking forward to switching our Jenkins builds to the released plugin.

**Pull request merged**
